name: ChatAuction
version: '${project.version}'
main: com.reloadedsmp.chatauction.ChatAuction
api-version: 1.18
authors: [ LoaiDev ]
depend: [ Vault ]
description: Auction Items using chat.
commands:
  auction:
    description: Auction your item.
    permission: auction.auction
  bid:
    description: Bid on an auction.
    permission: auction.bid
  auctionend:
    permission: auction.admin.end
    description: Force stop and finish the auction.
